<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php $this->extJs()->loadLibrary(); ?>
        <?php echo $this->headTitle('KJSencha Example Application') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink()
                    ->appendStylesheet($this->basepath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript()
                ->appendFile($this->basepath() . '/js/app/app.js') ?>
    </body>
</html>
